import csv, math, random, unicodedata, base64, sys
from collections import defaultdict

def norm(name):
    name = unicodedata.normalize("NFKD", str(name))
    name = name.lower().replace("+", " ").strip()
    toks = [t for t in "".join(c if "a" <= c <= "z" else " " for c in name).split() if t]
    HON = {"smt","shri","sri","sh","mr","mrs","ms","km","ku","kumari","kumar","dr","md","master","baby","miss","alias"}
    toks = [t for t in toks if t not in HON]
    return toks[0] if toks else ""

# ---- corpus 1: global (firstnames.csv) ----
GLOB = []  # (name, y, weight)
with open("firstnames.csv", encoding="utf-8", errors="replace") as f:
    r = csv.reader(f, delimiter=";"); header = next(r)
    for row in r:
        if len(row) < 3: continue
        g = row[1].strip()
        if g in ("M","1M","?M"): y=0
        elif g in ("F","1F","?F"): y=1
        else: continue
        n = norm(row[0])
        if len(n) < 2: continue
        GLOB.append((n, y, max(1, sum(1 for c in row[2:] if c.strip()))))

# ---- corpus 2: indian (public records, messy) -> aggregate ----
ind = defaultdict(lambda: [0,0])  # name -> [m,f]
for path, y in (("im.csv",0),("if.csv",1)):
    with open(path, encoding="utf-8", errors="replace") as f:
        r = csv.reader(f); next(r)
        for row in r:
            if not row: continue
            n = norm(row[0])
            if len(n) < 2: continue
            ind[n][y] += 1
INDIA = []
for n,(m,fc) in ind.items():
    tot = m + fc
    if tot < 2: continue
    maj = 1 if fc > m else 0
    purity = max(m,fc)/tot
    if purity < 0.8: continue
    INDIA.append((n, maj, tot))

random.seed(7)
random.shuffle(GLOB); random.shuffle(INDIA)
gcut, icut = int(len(GLOB)*0.9), int(len(INDIA)*0.9)
train = GLOB[:gcut] + [(n,y,min(w,25)) for n,y,w in INDIA[:icut]]
test_g, test_i = GLOB[gcut:], INDIA[icut:]
print(f"global {len(GLOB)}  india-agg {len(INDIA)}  train {len(train)}", file=sys.stderr)

def grams(n):
    s = "^" + n + "$"
    out = []
    for L in (2,3,4):
        out += [s[i:i+L] for i in range(len(s)-L+1)]
    return out

cm=defaultdict(float); cf=defaultdict(float); tm=tf=0.0
for n,y,w in train:
    for g in grams(n): (cf if y else cm)[g] += w
    if y: tf+=w
    else: tm+=w
vocab = set(cm)|set(cf); A=2.0
W={g: math.log((cf[g]+A)/(tf+A*len(vocab))) - math.log((cm[g]+A)/(tm+A*len(vocab))) for g in vocab}
prior = math.log(tf/tm)

# ---- exact table for confident/common names ----
seen = {}
for n,y,w in GLOB: seen[n] = seen.get(n, [0,0,0]); seen[n][y] += w; seen[n][2] = max(seen[n][2], w)
for n,y,w in INDIA: seen[n] = seen.get(n, [0,0,0]); seen[n][y] += min(w,25); seen[n][2] = max(seen[n][2], min(w,25))
table = {}
for n,(m,fc,mx) in seen.items():
    tot = m+fc
    if tot < 4: continue
    if max(m,fc)/tot < 0.85: continue
    table[n] = 1 if fc > m else 0
# rank by usage, cap
ranked_names = sorted(table, key=lambda n: -(seen[n][0]+seen[n][1]))[:3500]
table = {n: table[n] for n in ranked_names}
print(f"table size {len(table)} (fem {sum(table.values())})", file=sys.stderr)

# ---- quantized model ----
support={g: cm[g]+cf[g] for g in vocab}
ranked=sorted(vocab,key=lambda g:-abs(W[g])*math.log1p(support[g]))
keep=set(ranked[:6000]); SC=12.0
Q={g:max(-127,min(127,round(W[g]*SC))) for g in keep if round(W[g]*SC)!=0}
Wq={g:v/SC for g,v in Q.items()}

def pipeline(n):
    if n in table: return table[n]
    return 1 if (prior + sum(Wq.get(g,0.0) for g in grams(n))) > 0 else 0

def ev(ds,label):
    ok=tot=0; okw=totw=0
    for n,y,w in ds:
        p = pipeline(n); tot+=1; totw+=w
        if p==y: ok+=1; okw+=w
    print(f"{label}: {ok/tot:.3f} unweighted, {okw/totw:.3f} weighted (n={tot})", file=sys.stderr)

ev(test_g, "SHIPPED pipeline, held-out global")
ev([x for x in test_g if x[2]>=5], "  global common w>=5")
ev(test_i, "SHIPPED pipeline, held-out indian")
ev([x for x in test_i if x[2]>=5], "  indian common count>=5")

battery = [("maitree",1),("prakarsh",0),("prisha",1),("narendra",0),("aakriti",1),("ananya",1),
           ("aditya",0),("priya",1),("rahul",0),("sandra",1),("alexandra",1),("harsh",0),
           ("shruti",1),("vedant",0),("imran",0),("ayesha",1),("grace",1),("alan",0),
           ("barbara",1),("linus",0),("brendan",0),("yukiko",1),("kenji",0),("mei",1),
           ("chen",0),("olga",1),("dmitri",0),("fatima",1),("kwame",0),("amara",1)]
miss = [(n,want,pipeline(n)) for n,want in battery if pipeline(n)!=want]
print("battery misses:", miss if miss else "none", file=sys.stderr)

# ---- emit TS ----
items = sorted(Q.items())
gram_str = "".join(g.ljust(4,"|") for g,_ in items)
wts = base64.b64encode(bytes(v+128 for _,v in items)).decode()
femn = ",".join(sorted(n for n,y in table.items() if y==1))
mascn = ",".join(sorted(n for n,y in table.items() if y==0))
with open("gender-data.ts","w") as f:
    f.write("// AUTO-GENERATED by scripts/train_gender (name-gender table + char n-gram model).\n")
    f.write("// Sources: firstname-database (global usage) + Indian public-records names.\n")
    f.write("// Do not edit by hand; retrain instead.\n")
    f.write(f"export const GENDER_PRIOR = {prior:.4f};\nexport const GENDER_SCALE = {SC};\n")
    f.write(f"export const FEM_TABLE = {femn!r};\n")
    f.write(f"export const MASC_TABLE = {mascn!r};\n")
    f.write(f"export const GRAMS = {gram_str!r};\n")
    f.write(f"export const GRAM_WEIGHTS = {wts!r};\n")
print("wrote gender-data.ts", file=sys.stderr)
